services:
  # Backend API service
  - type: web
    name: student-feedback-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://student-feedback-frontend.onrender.com
    autoDeploy: true
    domains:
      - student-feedback-api.onrender.com

  # Frontend static site (deployed separately)
  - type: static
    name: student-feedback-frontend
    env: static
    region: ohio
    buildCommand: cd frontend && npm install && CI=false npm run build
    publishDir: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://student-feedback-api.onrender.com/api
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - student-feedback-frontend.onrender.com 