services:
  # Backend API service
  - type: web
    name: student-feedback-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: PORT
        value: 8080

  # Frontend static site
  - type: static
    name: student-feedback-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://student-feedback-api.onrender.com/api 