services:
  # Backend API service
  - type: web
    name: student-feedback-backend
    env: node
    region: ohio
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        value: https://student-feedback-frontend-i92f.onrender.com
    autoDeploy: true
    domains:
      - student-feedback-backend-q161.onrender.com

  # Frontend static site
  - type: static
    name: student-feedback-frontend
    env: static
    buildCommand: |
      cd frontend
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install
      CI=false GENERATE_SOURCEMAP=false npm run build
    publishDir: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://student-feedback-backend-q161.onrender.com
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://student-feedback-backend-q161.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - student-feedback-frontend-i92f.onrender.com 