version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend