name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd backend && npm install
      - name: Lint
        run: cd backend && npm run lint || true
      - name: Test
        run: echo "No tests defined"
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/student-feedback-backend -f docker/Dockerfile .
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: docker push your-dockerhub-username/student-feedback-backend