name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
      # Don't cancel other matrix jobs if one fails
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Cache node modules
    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Backend CI steps
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        npm ci
      continue-on-error: false

    - name: Run backend linting
      working-directory: ./backend
      run: |
        echo "Running backend linting..."
        npm run lint
      continue-on-error: true

    - name: Run backend tests
      working-directory: ./backend
      run: |
        echo "Running backend tests..."
        npm test
      continue-on-error: true

    # Frontend CI steps
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        echo "Installing frontend dependencies..."
        npm ci
      continue-on-error: false

    - name: Run frontend linting
      working-directory: ./frontend
      run: |
        echo "Running frontend linting..."
        npm run lint
      continue-on-error: true

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        echo "Running frontend tests..."
        npm test -- --watchAll=false --passWithNoTests
      continue-on-error: true

    - name: Build frontend
      working-directory: ./frontend
      run: |
        echo "Building frontend..."
        CI=false npm run build
      continue-on-error: false

    # Upload build artifacts
    - name: Upload frontend build
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/build/
        retention-days: 5 